### ISSUE TITLE
Compatibility with Latte

### ISSUE THREAD

**Issue by phoniq** [nextras/latte-macros#9]
Declaration of Nextras\Latte\Macros\RedefineMacro::install(Latte\Compiler $compiler) must be compatible with Latte\Macros\BlockMacros::install(Latte\Compiler $compiler): void

**Comment by hrach** [comment]
Hi, dou you have some specific need for this macro? It is currently not needed in latest nextras datagird.

**Comment by thorewi** [comment]
Some of us still uses the old datagrid, so it would be nice to fix it.

**Comment by hrach** [comment]
This has been working with old Latte. With the new Latte there is a new approach and it was workarounded in nextras datagrid directly.
